name: Linting
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  lint:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Run type check
        run: npx tsc
      - name: Run formatting check
        run: npx prettier -c .
      - name: Run lint check
        run: npx eslint . --ext .js,.jsx,.ts,.tsx
